name: Markdown Lint Check

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag ref to checkout'
        required: true
        type: string
      repository:
        description: 'Repository to checkout'
        required: true
        type: string
    secrets:
      token:
        description: 'Github token to use for comments'
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Print input values
      run: |
        echo "Ref: ${{inputs.ref}}"
        echo "Repository: ${{inputs.repository}}"
    - name: Checkout caller repository
      uses: actions/checkout@v3
      with:
        ref: ${{inputs.ref}}
        repository: ${{inputs.repository}}
        path: 'repo'

    - name: Checkout workflow repository
      uses: actions/checkout@v3
      with:
        repository: 'Security-Knowledge-Framework/GH-actions-markdown-linting' # The repository hosting the reusable workflow
        path: 'workflow-repo'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g markdownlint-cli

    - name: Run linter
      run: markdownlint ./repo --config ./workflow-repo/.github/configs/.markdownlint.json --ignore node_modules --ignore .github &> lint.txt
      working-directory: ${{github.workspace}}
          
    - name: Show Linting Issues
      if: failure()
      run: |
        cat lint.txt
        sed -i 's/```/triple-backtick/g' lint.txt
  
    - name: Attach Linting Issues
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Linting Issues
        path: lint.txt
    
