name: Markdown Terminology Lint Check

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag ref to checkout'
        required: true
        type: string
      repository:
        description: 'Repository to checkout'
        required: true
        type: string
    secrets:
      token:
        description: 'Github token to use for comments'
        required: true

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{inputs.ref}}
        repository: ${{inputs.repository}}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        npm install -g textlint
        npm install -g textlint-rule-terminology
    - name: Run textlint Check
      run: |
        touch log.txt
        # All markdown files, excluding .github
        # Use fix flag so that it goes through all files
        for FILE in $(find . -name '*.md' ! -path './.github/*'); do echo $FILE && textlint --config .github/configs/.textlintrc --fix --rule terminology $FILE | tee -a log.txt; done
        if grep -q  'Incorrect usage' log.txt ; then exit 1 ; else echo -e \"No terminology issues found.\"; fi
    - name: Show Mistakes
      if: failure()
      run: |
        cat log.txt
        cat log.txt | grep -v '✔ Fixed' | tr '✔' '✖' >mistakes.txt
    - name: Attach Mistakes
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: Terminology Mistakes
        path: mistakes.txt
